version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: npm
    directories: [/engine, /ui/editor]
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget:
        patterns: ['*']
  - package-ecosystem: pip
    directory: /.github/security
    schedule:
      interval: weekly
