<#
.SYNOPSIS
    Generates the analyzer's keyword table from the reference implementation.

.DESCRIPTION
    Canonical capitalization is presentation: it is what the editor shows the user. Two hand written
    copies of it would drift, and the drift would be invisible until someone noticed a keyword cased
    differently in one product than the other. So one copy is authored and the other is generated.

    Re-run after changing the reference table. The output is committed, so a build never depends on
    the reference checkout being present.
#>
[CmdletBinding()]
param(
    [string] $Source,
    [string] $Output
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$here = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$repoRoot = Split-Path -Parent $here

if (-not $Source) { $Source = Join-Path (Split-Path -Parent $repoRoot) 'xlide_vscode\src\analyzer\lexer\keywordTable.ts' }
if (-not $Output) { $Output = Join-Path $repoRoot 'src\Xlide.Vba.Analysis\Lexing\KeywordTable.g.cs' }

if (-not (Test-Path $Source)) {
    throw "The reference keyword table was not found at $Source."
}

$text = Get-Content $Source -Raw

function Get-Array {
    param([string] $Name)

    $pattern = "export const $Name(?:\s*:\s*readonly string\[\])?\s*=\s*\[(?<body>[^\]]*)\]"
    $match = [regex]::Match($text, $pattern, 'Singleline')
    if (-not $match.Success) { throw "Could not find $Name in the reference table." }

    $words = New-Object System.Collections.Generic.List[string]
    foreach ($literal in [regex]::Matches($match.Groups['body'].Value, "'([^']+)'")) {
        $words.Add($literal.Groups[1].Value)
    }

    return , $words.ToArray()
}

# Three sets, not two, and the distinction is easy to miss.
#
# Keyword-cased words are what the lexer reports as keywords and what the editor capitalizes.
#
# Words reserved for the implementation, such as the attribute marker in a module header, can never
# be a user-defined name, but they are NOT keyword-cased: the reference lexes them as identifiers.
# Folding them into the cased set makes every module header disagree, which is exactly what the
# comparison against the reference caught.
#
# Contextual words are not reserved at all. They are ordinary names that the editor capitalizes
# where they are meaningful, so they remain usable as identifiers.
$casingGroups = @(
    'STATEMENT_KEYWORDS', 'MARKER_KEYWORDS', 'OPERATOR_IDENTIFIERS', 'RESERVED_NAMES',
    'SPECIAL_FORMS', 'RESERVED_TYPE_IDENTIFIERS', 'LITERAL_IDENTIFIERS', 'FUTURE_RESERVED'
)

$cased = New-Object System.Collections.Generic.List[string]
foreach ($group in $casingGroups) {
    foreach ($word in (Get-Array $group)) { $cased.Add($word) }
}

# Rem is declared on its own in the reference and is keyword-cased.
$remMatch = [regex]::Match($text, "export const REM_KEYWORD\s*=\s*'([^']+)'")
if ($remMatch.Success) { $cased.Add($remMatch.Groups[1].Value) }

$implementation = Get-Array 'RESERVED_FOR_IMPLEMENTATION_USE'
$contextual = Get-Array 'CONTEXTUAL_KEYWORDS'

$cased = @($cased | Sort-Object -Unique)
$implementation = @($implementation | Where-Object { $cased -notcontains $_ } | Sort-Object -Unique)
$contextual = @($contextual | Where-Object { $cased -notcontains $_ } | Sort-Object -Unique)

$builder = New-Object System.Text.StringBuilder
[void] $builder.AppendLine('// Generated by tools/Generate-KeywordTable.ps1. Do not edit by hand.')
[void] $builder.AppendLine('//')
[void] $builder.AppendLine('// Canonical capitalization of VBA keywords, per MS-VBAL section 3.3.5.2, in the casing the')
[void] $builder.AppendLine('// editor itself emits. Identifiers are case insensitive, so every lookup is by lowercase.')
[void] $builder.AppendLine()
[void] $builder.AppendLine('namespace Xlide.Vba.Analysis.Lexing;')
[void] $builder.AppendLine()
[void] $builder.AppendLine('public static partial class KeywordTable')
[void] $builder.AppendLine('{')
[void] $builder.AppendLine("    /// <summary>Words the lexer reports as keywords and the editor capitalizes.</summary>")
[void] $builder.AppendLine('    private static readonly string[] CasedWords =')
[void] $builder.AppendLine('    [')
foreach ($word in $cased) { [void] $builder.AppendLine("        `"$word`",") }
[void] $builder.AppendLine('    ];')
[void] $builder.AppendLine()
[void] $builder.AppendLine("    /// <summary>")
[void] $builder.AppendLine("    /// Reserved for the implementation. Never a user-defined name, but not keyword-cased either:")
[void] $builder.AppendLine("    /// these lex as identifiers.")
[void] $builder.AppendLine("    /// </summary>")
[void] $builder.AppendLine('    private static readonly string[] ImplementationWords =')
[void] $builder.AppendLine('    [')
foreach ($word in $implementation) { [void] $builder.AppendLine("        `"$word`",") }
[void] $builder.AppendLine('    ];')
[void] $builder.AppendLine()
[void] $builder.AppendLine("    /// <summary>Not reserved, but capitalized by the editor where they are meaningful.</summary>")
[void] $builder.AppendLine('    private static readonly string[] ContextualWords =')
[void] $builder.AppendLine('    [')
foreach ($word in $contextual) { [void] $builder.AppendLine("        `"$word`",") }
[void] $builder.AppendLine('    ];')
[void] $builder.AppendLine('}')

New-Item -ItemType Directory -Force -Path (Split-Path $Output) | Out-Null
[System.IO.File]::WriteAllText($Output, $builder.ToString(), (New-Object System.Text.UTF8Encoding $false))

Write-Host ("Wrote {0}: {1} cased, {2} implementation-reserved, {3} contextual." -f
    $Output, $cased.Count, $implementation.Count, $contextual.Count)
